### ISSUE TITLE
No p4 setup on following the quickstart instructions

### ISSUE THREAD

**Issue by koyan** [greenpeace/planet4-docker-compose#2]
After following the quickstart instructions, the 8 (expected?) docker images were generated and run. But when navigating to https://test.planet4.dev, instead of the expected planet4 environment, I got the default wordpress initial setup page. (setup-config.php) .

**Comment by 27Bslash6** [comment]
Thanks for this, was a breaking change during development on [greenpeace/planet4-docker](https://github.com/greenpeace/planet4-docker) today.  Highlights the need for more complete test coverage over all projects.

Closing as tested functional now.
