### ISSUE TITLE
envsubst not present on OS X

### ISSUE THREAD

**Issue by techieshark** [greenpeace/planet4-docker-compose#36]
The `Makefile` uses the `envsubst` command, and so I'm seeing `make` fails on OS X.

The command didn't seem to be available but I was able to install it via `homebrew`:
https://stackoverflow.com/a/23622446/1024811

Perhaps it should be listed in the README as a requirement?

**Comment by koyan** [comment]
Thanks. 
Done. https://github.com/greenpeace/planet4-docker-compose/commit/25b77ceb175b32c9ef3c66de8441bfe278349845
