### ISSUE TITLE
GPNZ  - Wordpress Admin Credential Failure

### ISSUE THREAD

**Issue by altan-me** [greenpeace/planet4-docker-compose#4]
Host: Debian 9
Allowed Ports: 80, 443

Followed Quick Start guide however the "make wppass" credentials do not work 
Any guidance as to which logs i can look at or what i can check?

`docker-compose version 1.20.1, build 5d8c71b`
`Docker version 18.03.0-ce, build 0520e24 `

![screenshot from 2018-04-05 14-46-32](https://user-images.githubusercontent.com/12891722/38344930-626ec82c-38e0-11e8-8967-28bf695e3084.png)

**Comment by altan-me** [comment]
So: https://test.planet4.dev/wp-admin
redirects to:
https://test.planet4.dev/international/wp-login.php?redirect_to=https%3A%2F%2Ftest.planet4.dev%2Fwp-admin%2F&reauth=1
The wordpress credentials do not work here:

However if you navigate direct to: https://test.planet4.dev/wp-login.php
Credentials work.

Is this intentional ?

**Comment by 27Bslash6** [comment]
Not intentional. That's a curious artifact of WP / nginx redirections

Seems to work as expected if you visit:
https://test.planet4.dev/wp-login.php
https://test.planet4.dev/international/wp-login.php
https://test.planet4.dev/international/admin

But not in any combination of /wp-admin that I tested.  Interesting...

**Comment by 27Bslash6** [comment]
Updated documentation to point to a more helpful URL in https://github.com/greenpeace/planet4-docker-compose/commit/7f15c01f5b6a03e6444a523d1fff3e509310d309

If anyone discoveres exactly why wp-admin redirects aren't happy please advise.

**Comment by 27Bslash6** [comment]
Issue resolved some time ago, in the switch to LUA path processing.
