### ISSUE TITLE
Master Theme and plugins are not git repos

### ISSUE THREAD

**Issue by comzeradd** [greenpeace/planet4-docker-compose#9]
The medialibrary plugin that lives inside `persistence/app/public/wp-content/plugins/planet4-plugin-medialibrary` is not a git repo. The `.git` folder is completely missing.

**Comment by pablocubico** [comment]
The master theme and other plugins are not git repos either when you initialize a new environment. I'll edit this issue's description to reflect that.

**Comment by 27Bslash6** [comment]
Closed in #21
